### ISSUE TITLE
Publish 0.4.0 to npm?

### ISSUE THREAD

**Issue by bjmiller** [moveline/gulp-env#9]
Currently, npm has this at 0.2.0, and that version doesn't behave as expected based on the current README here.  Please publish 0.4.0 to npm, so it matches current master.

**Comment by JayTurn** [comment]
+1 for this as gulp-env doesn't work at all when attempting to retrieve it via npm. The repository for gulp-env is registered with git://github.com/moveline/gulp-env.git so I have found I am getting an index.js file that looks as follows:

```
'use strict';

module.exports = function(options) {
  if (options.file) {
    var env = require(process.cwd() + "/" + options.file);

    for (var prop in env) {
      process.env[prop] = env[prop];
    }
  }

  if (options.vars) {
    var vars = options.vars
    for (var prop in vars) {
      process.env[prop] = vars[prop];
    }
  }
}
```

**Comment by russmatney** [comment]
published the latest with local changes to the package.json, should resolve this issue.
